# Generated by Django 4.2.19 on 2025-03-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_contact_email_alter_item_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
